<a href="https://colab.research.google.com/github/satish-1999/Fake_News_D/blob/main/FAKE_1st_text%2Btitle_count_vectorizer_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from wordcloud import WordCloud, STOPWORDS 

In [ ]:
data=pd.read_csv('/content/drive/MyDrive/FAKE NEWS/train.csv')


In [ ]:
data.drop('author',axis=1)

id  ... label
0          0  ...     1
1          1  ...     0
2          2  ...     1
3          3  ...     1
4          4  ...     1
...      ...  ...   ...
20795  20795  ...     0
20796  20796  ...     0
20797  20797  ...     0
20798  20798  ...     1
20799  20799  ...     1

[20800 rows x 4 columns]

In [ ]:
data['news'] = data['text'] + data['title']

In [ ]:
y=data['label']

In [ ]:
len(y)

20800

In [ ]:
data.head(10)

id  ...                                               news
0   0  ...  House Dem Aide: We Didn’t Even See Comey’s Let...
1   1  ...  Ever get the feeling your life circles the rou...
2   2  ...  Why the Truth Might Get You Fired October 29, ...
3   3  ...  Videos 15 Civilians Killed In Single US Airstr...
4   4  ...  Print \nAn Iranian woman has been sentenced to...
5   5  ...  In these trying times, Jackie Mason is the Voi...
6   6  ...  Ever wonder how Britain’s most iconic pop pian...
7   7  ...  PARIS  —   France chose an idealistic, traditi...
8   8  ...  Donald J. Trump is scheduled to make a highly ...
9   9  ...  A week before Michael T. Flynn resigned as nat...

[10 rows x 6 columns]

In [ ]:
df=data.iloc[:,3].values

In [ ]:
df

array(['House Dem Aide: We Didn’t Even See Comey’s Letter Until Jason Chaffetz Tweeted It By Darrell Lucus on October 30, 2016 Subscribe Jason Chaffetz on the stump in American Fork, Utah ( image courtesy Michael Jolley, available under a Creative Commons-BY license) \nWith apologies to Keith Olbermann, there is no doubt who the Worst Person in The World is this week–FBI Director James Comey. But according to a House Democratic aide, it looks like we also know who the second-worst person is as well. It turns out that when Comey sent his now-infamous letter announcing that the FBI was looking into emails that may be related to Hillary Clinton’s email server, the ranking Democrats on the relevant committees didn’t hear about it from Comey. They found out via a tweet from one of the Republican committee chairmen. \nAs we now know, Comey notified the Republican chairmen and Democratic ranking members of the House Intelligence, Judiciary, and Oversight committees that his agency was reviewi

In [ ]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus = []
for i in range(0,20800):
  review = re.sub('[^a-zA-Z]', ' ', str(data['news'][i]))
  review = review.lower()
  review = review.split()
  ps = PorterStemmer()
  all_stopwords = stopwords.words('english')
  all_stopwords.remove('not')
  review = [ps.stem(word) for word in review if not word in set(all_stopwords)]
  review = ' '.join(review)
  corpus.append(review)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 5000,ngram_range=(1,1))
x = cv.fit_transform(corpus).toarray()
#y = data.iloc[:, 0].values
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2, random_state = 0)

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier1 = LogisticRegression(random_state = 0)
classifier1.fit(x_train, y_train)
y_pred1=classifier1.predict(x_test)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier2 = KNeighborsClassifier(n_neighbors = 10, metric = 'minkowski', p = 2)
classifier2.fit(x_train, y_train)
y_pred2=classifier2.predict(x_test)

In [ ]:
from sklearn.svm import SVC
classifier3 = SVC(kernel = 'linear', random_state = 0)
classifier3.fit(x_train, y_train)
y_pred3=classifier3.predict(x_test)

In [ ]:
from sklearn.naive_bayes import MultinomialNB
classifier4=MultinomialNB()
classifier4.fit(x_train, y_train)
y_pred4=classifier4.predict(x_test)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier5 = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier5.fit(x_train, y_train)
y_pred5=classifier5.predict(x_test)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier6 = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier6.fit(x_train, y_train)
y_pred6=classifier6.predict(x_test)

In [ ]:
from sklearn.linear_model import  SGDClassifier
classifier7 =  SGDClassifier(random_state=42)
classifier7.fit(x_train, y_train) 
y_pred7 = classifier7.predict(x_test)

In [ ]:
from sklearn.linear_model import PassiveAggressiveClassifier
classifier8 = PassiveAggressiveClassifier()
classifier8.fit(x_train, y_train)
y_pred8=classifier8.predict(x_test)

In [ ]:
from sklearn.ensemble import AdaBoostClassifier
classifier9 = AdaBoostClassifier(n_estimators=100, random_state=0)
classifier9.fit(x_train, y_train)
y_pred9=classifier9.predict(x_test)

In [ ]:
from sklearn.ensemble import VotingClassifier
classifier10 = VotingClassifier(estimators=[('lr', classifier1), ('knn', classifier2), ('svc', classifier3)], voting='hard')
classifier10.fit(x_train, y_train)
y_pred10 = classifier10.predict(x_test)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [ ]:
from sklearn.metrics import confusion_matrix,plot_confusion_matrix, balanced_accuracy_score, accuracy_score ,f1_score, precision_score, recall_score,classification_report, plot_roc_curve,roc_auc_score
cm = confusion_matrix(y_test, y_pred1)
print(cm)
#plot_confusion_matrix(classifier,x_test,y_test,values_format='d')
#plt.show()
print(accuracy_score(y_test, y_pred1))
print(f1_score(y_test, y_pred1,average='macro'))
print(precision_score(y_test,y_pred1,average='macro'))
print(recall_score(y_test,y_pred1,average='macro'))
print(balanced_accuracy_score(y_test,y_pred1))
print(classification_report(y_test, y_pred1))

#plot_roc_curve(classifier1,x_test,y_test)

print(roc_auc_score(y_test,y_pred1,average='macro'))

[[1931  115]
 [  87 2027]]
0.9514423076923076
0.9514164347877567
0.951599933002603
0.9513192781725146
0.9513192781725146
              precision    recall  f1-score   support

           0       0.96      0.94      0.95      2046
           1       0.95      0.96      0.95      2114

    accuracy                           0.95      4160
   macro avg       0.95      0.95      0.95      4160
weighted avg       0.95      0.95      0.95      4160

0.9513192781725146


In [ ]:
from sklearn.metrics import confusion_matrix,plot_confusion_matrix, balanced_accuracy_score, accuracy_score ,f1_score, precision_score, recall_score,classification_report, plot_roc_curve,roc_auc_score
cm = confusion_matrix(y_test, y_pred2)
print(cm)
#plot_confusion_matrix(classifier,x_test,y_test,values_format='d')
#plt.show()
print(accuracy_score(y_test, y_pred2))
print(f1_score(y_test, y_pred2,average='macro'))
print(precision_score(y_test,y_pred2,average='macro'))
print(recall_score(y_test,y_pred2,average='macro'))
print(balanced_accuracy_score(y_test,y_pred2))
print(classification_report(y_test, y_pred2))

#plot_roc_curve(classifier1,x_test,y_test)

print(roc_auc_score(y_test,y_pred2,average='macro'))

[[1231  815]
 [ 111 2003]]
0.7774038461538462
0.769464480811528
0.8140377115816039
0.7745773417638404
0.7745773417638404
              precision    recall  f1-score   support

           0       0.92      0.60      0.73      2046
           1       0.71      0.95      0.81      2114

    accuracy                           0.78      4160
   macro avg       0.81      0.77      0.77      4160
weighted avg       0.81      0.78      0.77      4160

0.7745773417638404


In [ ]:
from sklearn.metrics import confusion_matrix,plot_confusion_matrix,accuracy_score ,f1_score, precision_score, recall_score,classification_report, plot_roc_curve,roc_auc_score
cm = confusion_matrix(y_test, y_pred3)
print(cm)
#plot_confusion_matrix(classifier,x_test,y_test,values_format='d')
#plt.show()
print(accuracy_score(y_test, y_pred3))
print(f1_score(y_test, y_pred3,average='macro'))
print(precision_score(y_test,y_pred3,average='macro'))
print(recall_score(y_test,y_pred3,average='macro'))
print(balanced_accuracy_score(y_test,y_pred3))
print(classification_report(y_test, y_pred3))

#plot_roc_curve(classifier1,x_test,y_test)

print(roc_auc_score(y_test,y_pred3,average='macro'))

[[1918  128]
 [  98 2016]]
0.9456730769230769
0.9456429106482217
0.9458436981757877
0.9455406446434005
0.9455406446434005
              precision    recall  f1-score   support

           0       0.95      0.94      0.94      2046
           1       0.94      0.95      0.95      2114

    accuracy                           0.95      4160
   macro avg       0.95      0.95      0.95      4160
weighted avg       0.95      0.95      0.95      4160

0.9455406446434005


In [ ]:
from sklearn.metrics import confusion_matrix,plot_confusion_matrix,accuracy_score ,f1_score, precision_score, recall_score,classification_report, plot_roc_curve,roc_auc_score
cm = confusion_matrix(y_test, y_pred4)
print(cm)
#plot_confusion_matrix(classifier,x_test,y_test,values_format='d')
#plt.show()
print(accuracy_score(y_test, y_pred4))
print(f1_score(y_test, y_pred4,average='macro'))
print(precision_score(y_test,y_pred4,average='macro'))
print(recall_score(y_test,y_pred4,average='macro'))
print(balanced_accuracy_score(y_test,y_pred4))
print(classification_report(y_test, y_pred4))

#plot_roc_curve(classifier1,x_test,y_test)

print(roc_auc_score(y_test,y_pred4,average='macro'))

[[1878  168]
 [ 317 1797]]
0.8834134615384616
0.883369243805971
0.8850423411987689
0.8839679333697705
0.8839679333697705
              precision    recall  f1-score   support

           0       0.86      0.92      0.89      2046
           1       0.91      0.85      0.88      2114

    accuracy                           0.88      4160
   macro avg       0.89      0.88      0.88      4160
weighted avg       0.89      0.88      0.88      4160

0.8839679333697706


In [ ]:
from sklearn.metrics import confusion_matrix,plot_confusion_matrix,accuracy_score ,f1_score, precision_score, recall_score,classification_report, plot_roc_curve,roc_auc_score
cm = confusion_matrix(y_test, y_pred5)
print(cm)
#plot_confusion_matrix(classifier,x_test,y_test,values_format='d')
#plt.show()
print(accuracy_score(y_test, y_pred5))
print(f1_score(y_test, y_pred5,average='macro'))
print(precision_score(y_test,y_pred5,average='macro'))
print(recall_score(y_test,y_pred5,average='macro'))
print(balanced_accuracy_score(y_test,y_pred5))
print(classification_report(y_test, y_pred5))

#plot_roc_curve(classifier1,x_test,y_test)

print(roc_auc_score(y_test,y_pred5,average='macro'))

[[1901  145]
 [ 140 1974]]
0.9314903846153846
0.9314692816083632
0.931488834716532
0.9314524221061286
0.9314524221061286
              precision    recall  f1-score   support

           0       0.93      0.93      0.93      2046
           1       0.93      0.93      0.93      2114

    accuracy                           0.93      4160
   macro avg       0.93      0.93      0.93      4160
weighted avg       0.93      0.93      0.93      4160

0.9314524221061286


In [ ]:
from sklearn.metrics import confusion_matrix,plot_confusion_matrix,accuracy_score ,f1_score, precision_score, recall_score,classification_report, plot_roc_curve,roc_auc_score
cm = confusion_matrix(y_test, y_pred6)
print(cm)
#plot_confusion_matrix(classifier,x_test,y_test,values_format='d')
#plt.show()
print(accuracy_score(y_test, y_pred6))
print(f1_score(y_test, y_pred6,average='macro'))
print(precision_score(y_test,y_pred6,average='macro'))
print(recall_score(y_test,y_pred6,average='macro'))
print(balanced_accuracy_score(y_test,y_pred6))
print(classification_report(y_test, y_pred6))

#plot_roc_curve(classifier1,x_test,y_test)

print(roc_auc_score(y_test,y_pred6,average='macro'))

[[1934  112]
 [ 291 1823]]
0.903125
0.9030559791465805
0.9056661730975815
0.9038026525208751
0.9038026525208751
              precision    recall  f1-score   support

           0       0.87      0.95      0.91      2046
           1       0.94      0.86      0.90      2114

    accuracy                           0.90      4160
   macro avg       0.91      0.90      0.90      4160
weighted avg       0.91      0.90      0.90      4160

0.9038026525208751


In [ ]:
from sklearn.metrics import confusion_matrix,plot_confusion_matrix,accuracy_score ,f1_score, precision_score, recall_score,classification_report, plot_roc_curve,roc_auc_score
cm = confusion_matrix(y_test, y_pred7)
print(cm)
#plot_confusion_matrix(classifier,x_test,y_test,values_format='d')
#plt.show()
print(accuracy_score(y_test, y_pred7))
print(f1_score(y_test, y_pred7,average='macro'))
print(precision_score(y_test,y_pred7,average='macro'))
print(recall_score(y_test,y_pred7,average='macro'))
print(balanced_accuracy_score(y_test,y_pred7))
print(classification_report(y_test, y_pred7))

#plot_roc_curve(classifier1,x_test,y_test)

print(roc_auc_score(y_test,y_pred7,average='macro'))

[[1915  131]
 [  90 2024]]
0.946875
0.9468385024643918
0.9471616781711614
0.9466996544010002
0.9466996544010002
              precision    recall  f1-score   support

           0       0.96      0.94      0.95      2046
           1       0.94      0.96      0.95      2114

    accuracy                           0.95      4160
   macro avg       0.95      0.95      0.95      4160
weighted avg       0.95      0.95      0.95      4160

0.9466996544010002


In [ ]:
from sklearn.metrics import confusion_matrix,plot_confusion_matrix, balanced_accuracy_score, accuracy_score ,f1_score, precision_score, recall_score,classification_report, plot_roc_curve,roc_auc_score
cm = confusion_matrix(y_test, y_pred8)
print(cm)
#plot_confusion_matrix(classifier,x_test,y_test,values_format='d')
#plt.show()
print(accuracy_score(y_test, y_pred8))
print(f1_score(y_test, y_pred8,average='macro'))
print(precision_score(y_test,y_pred8,average='macro'))
print(recall_score(y_test,y_pred8,average='macro'))
print(balanced_accuracy_score(y_test,y_pred8))
print(classification_report(y_test, y_pred8))

#plot_roc_curve(classifier1,x_test,y_test)

print(roc_auc_score(y_test,y_pred8,average='macro'))

[[1922  124]
 [  92 2022]]
0.948076923076923
0.9480469021022688
0.9482689209087183
0.9479372724405837
0.9479372724405837
              precision    recall  f1-score   support

           0       0.95      0.94      0.95      2046
           1       0.94      0.96      0.95      2114

    accuracy                           0.95      4160
   macro avg       0.95      0.95      0.95      4160
weighted avg       0.95      0.95      0.95      4160

0.9479372724405838


In [ ]:
from sklearn.metrics import confusion_matrix,plot_confusion_matrix, balanced_accuracy_score, accuracy_score ,f1_score, precision_score, recall_score,classification_report, plot_roc_curve,roc_auc_score
cm = confusion_matrix(y_test, y_pred9)
print(cm)
#plot_confusion_matrix(classifier,x_test,y_test,values_format='d')
#plt.show()
print(accuracy_score(y_test, y_pred9))
print(f1_score(y_test, y_pred9,average='macro'))
print(precision_score(y_test,y_pred9,average='macro'))
print(recall_score(y_test,y_pred9,average='macro'))
print(balanced_accuracy_score(y_test,y_pred9))
print(classification_report(y_test, y_pred9))

#plot_roc_curve(classifier1,x_test,y_test)

print(roc_auc_score(y_test,y_pred9,average='macro'))

[[1954   92]
 [  85 2029]]
0.9574519230769231
0.9574380887833653
0.9574685661658018
0.9574130384320515
0.9574130384320515
              precision    recall  f1-score   support

           0       0.96      0.96      0.96      2046
           1       0.96      0.96      0.96      2114

    accuracy                           0.96      4160
   macro avg       0.96      0.96      0.96      4160
weighted avg       0.96      0.96      0.96      4160

0.9574130384320515


In [ ]:
from sklearn.metrics import confusion_matrix,plot_confusion_matrix, balanced_accuracy_score, accuracy_score ,f1_score, precision_score, recall_score,classification_report, plot_roc_curve,roc_auc_score
cm = confusion_matrix(y_test, y_pred10)
print(cm)
#plot_confusion_matrix(classifier,x_test,y_test,values_format='d')
#plt.show()
print(accuracy_score(y_test, y_pred10))
print(f1_score(y_test, y_pred10,average='macro'))
print(precision_score(y_test,y_pred10,average='macro'))
print(recall_score(y_test,y_pred10,average='macro'))
print(balanced_accuracy_score(y_test,y_pred10))
print(classification_report(y_test, y_pred10))

#plot_roc_curve(classifier1,x_test,y_test)

print(roc_auc_score(y_test,y_pred10,average='macro'))

[[1910  136]
 [  83 2031]]
0.9473557692307693
0.9473111930922975
0.9477973321947536
0.9471333871568863
0.9471333871568863
              precision    recall  f1-score   support

           0       0.96      0.93      0.95      2046
           1       0.94      0.96      0.95      2114

    accuracy                           0.95      4160
   macro avg       0.95      0.95      0.95      4160
weighted avg       0.95      0.95      0.95      4160

0.9471333871568864
