<a href="https://colab.research.google.com/github/satish-1999/Fake_News_D/blob/main/FAKE_1st_text_count_vectorizer_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from wordcloud import WordCloud, STOPWORDS 

In [ ]:
data=pd.read_csv('/content/drive/MyDrive/FAKE NEWS/train.csv')


In [ ]:
data.drop('author',axis=1)

id  ... label
0          0  ...     1
1          1  ...     0
2          2  ...     1
3          3  ...     1
4          4  ...     1
...      ...  ...   ...
20795  20795  ...     0
20796  20796  ...     0
20797  20797  ...     0
20798  20798  ...     1
20799  20799  ...     1

[20800 rows x 4 columns]

In [ ]:
y=data['label']

In [ ]:
len(y)

20800

In [ ]:
data.head(10)

id  ... label
0   0  ...     1
1   1  ...     0
2   2  ...     1
3   3  ...     1
4   4  ...     1
5   5  ...     0
6   6  ...     1
7   7  ...     0
8   8  ...     0
9   9  ...     0

[10 rows x 5 columns]

In [ ]:
df=data.iloc[:,3].values

In [ ]:
df

array(['House Dem Aide: We Didn’t Even See Comey’s Letter Until Jason Chaffetz Tweeted It By Darrell Lucus on October 30, 2016 Subscribe Jason Chaffetz on the stump in American Fork, Utah ( image courtesy Michael Jolley, available under a Creative Commons-BY license) \nWith apologies to Keith Olbermann, there is no doubt who the Worst Person in The World is this week–FBI Director James Comey. But according to a House Democratic aide, it looks like we also know who the second-worst person is as well. It turns out that when Comey sent his now-infamous letter announcing that the FBI was looking into emails that may be related to Hillary Clinton’s email server, the ranking Democrats on the relevant committees didn’t hear about it from Comey. They found out via a tweet from one of the Republican committee chairmen. \nAs we now know, Comey notified the Republican chairmen and Democratic ranking members of the House Intelligence, Judiciary, and Oversight committees that his agency was reviewi

In [ ]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus = []
for i in range(0,20800):
  review = re.sub('[^a-zA-Z]', ' ', str(data['text'][i]))
  review = review.lower()
  review = review.split()
  ps = PorterStemmer()
  all_stopwords = stopwords.words('english')
  all_stopwords.remove('not')
  review = [ps.stem(word) for word in review if not word in set(all_stopwords)]
  review = ' '.join(review)
  corpus.append(review)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 5000,ngram_range=(1,1))
x = cv.fit_transform(corpus).toarray()
#y = data.iloc[:, 0].values
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2, random_state = 0)

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier1 = LogisticRegression(random_state = 0)
classifier1.fit(x_train, y_train)
y_pred1=classifier1.predict(x_test)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier2 = KNeighborsClassifier(n_neighbors = 10, metric = 'minkowski', p = 2)
classifier2.fit(x_train, y_train)
y_pred2=classifier2.predict(x_test)

In [ ]:
from sklearn.svm import SVC
classifier3 = SVC(kernel = 'linear', random_state = 0)
classifier3.fit(x_train, y_train)
y_pred3=classifier3.predict(x_test)

In [ ]:
from sklearn.naive_bayes import MultinomialNB
classifier4=MultinomialNB()
classifier4.fit(x_train, y_train)
y_pred4=classifier4.predict(x_test)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier5 = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier5.fit(x_train, y_train)
y_pred5=classifier5.predict(x_test)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier6 = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier6.fit(x_train, y_train)
y_pred6=classifier6.predict(x_test)

In [ ]:
from sklearn.linear_model import  SGDClassifier
classifier7 =  SGDClassifier(random_state=42)
classifier7.fit(x_train, y_train) 
y_pred7 = classifier7.predict(x_test)

In [ ]:
from sklearn.linear_model import PassiveAggressiveClassifier
classifier8 = PassiveAggressiveClassifier()
classifier8.fit(x_train, y_train)
y_pred8=classifier8.predict(x_test)

In [ ]:
from sklearn.ensemble import AdaBoostClassifier
classifier9 = AdaBoostClassifier(n_estimators=100, random_state=0)
classifier9.fit(x_train, y_train)
y_pred9=classifier9.predict(x_test)

In [ ]:
from sklearn.ensemble import VotingClassifier
classifier10 = VotingClassifier(estimators=[('lr', classifier1), ('knn', classifier2), ('svc', classifier3)], voting='hard')
classifier10.fit(x_train, y_train)
y_pred10 = classifier10.predict(x_test)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [ ]:
from sklearn.metrics import confusion_matrix,plot_confusion_matrix, balanced_accuracy_score, accuracy_score ,f1_score, precision_score, recall_score,classification_report, plot_roc_curve,roc_auc_score
cm = confusion_matrix(y_test, y_pred1)
print(cm)
#plot_confusion_matrix(classifier,x_test,y_test,values_format='d')
#plt.show()
print(accuracy_score(y_test, y_pred1))
print(f1_score(y_test, y_pred1,average='macro'))
print(precision_score(y_test,y_pred1,average='macro'))
print(recall_score(y_test,y_pred1,average='macro'))
print(balanced_accuracy_score(y_test,y_pred1))
print(classification_report(y_test, y_pred1))

#plot_roc_curve(classifier1,x_test,y_test)

print(roc_auc_score(y_test,y_pred1,average='macro'))

[[1917  129]
 [ 104 2010]]
0.9439903846153846
0.943962378109298
0.9441158855856424
0.9438771546761292
0.9438771546761292
              precision    recall  f1-score   support

           0       0.95      0.94      0.94      2046
           1       0.94      0.95      0.95      2114

    accuracy                           0.94      4160
   macro avg       0.94      0.94      0.94      4160
weighted avg       0.94      0.94      0.94      4160

0.9438771546761293


In [ ]:
from sklearn.metrics import confusion_matrix,plot_confusion_matrix, balanced_accuracy_score, accuracy_score ,f1_score, precision_score, recall_score,classification_report, plot_roc_curve,roc_auc_score
cm = confusion_matrix(y_test, y_pred2)
print(cm)
#plot_confusion_matrix(classifier,x_test,y_test,values_format='d')
#plt.show()
print(accuracy_score(y_test, y_pred2))
print(f1_score(y_test, y_pred2,average='macro'))
print(precision_score(y_test,y_pred2,average='macro'))
print(recall_score(y_test,y_pred2,average='macro'))
print(balanced_accuracy_score(y_test,y_pred2))
print(classification_report(y_test, y_pred2))

#plot_roc_curve(classifier1,x_test,y_test)

print(roc_auc_score(y_test,y_pred2,average='macro'))

[[1242  804]
 [ 111 2003]]
0.7800480769230769
0.7724326799441772
0.8157666492621787
0.7772655138068512
0.7772655138068512
              precision    recall  f1-score   support

           0       0.92      0.61      0.73      2046
           1       0.71      0.95      0.81      2114

    accuracy                           0.78      4160
   macro avg       0.82      0.78      0.77      4160
weighted avg       0.81      0.78      0.77      4160

0.7772655138068512


In [ ]:
from sklearn.metrics import confusion_matrix,plot_confusion_matrix,accuracy_score ,f1_score, precision_score, recall_score,classification_report, plot_roc_curve,roc_auc_score
cm = confusion_matrix(y_test, y_pred3)
print(cm)
#plot_confusion_matrix(classifier,x_test,y_test,values_format='d')
#plt.show()
print(accuracy_score(y_test, y_pred3))
print(f1_score(y_test, y_pred3,average='macro'))
print(precision_score(y_test,y_pred3,average='macro'))
print(recall_score(y_test,y_pred3,average='macro'))
print(balanced_accuracy_score(y_test,y_pred3))
print(classification_report(y_test, y_pred3))

#plot_roc_curve(classifier1,x_test,y_test)

print(roc_auc_score(y_test,y_pred3,average='macro'))

[[1887  159]
 [ 128 1986]]
0.9310096153846154
0.9309705206449266
0.9311752763365666
0.9308693336144735
0.9308693336144735
              precision    recall  f1-score   support

           0       0.94      0.92      0.93      2046
           1       0.93      0.94      0.93      2114

    accuracy                           0.93      4160
   macro avg       0.93      0.93      0.93      4160
weighted avg       0.93      0.93      0.93      4160

0.9308693336144734


In [ ]:
from sklearn.metrics import confusion_matrix,plot_confusion_matrix,accuracy_score ,f1_score, precision_score, recall_score,classification_report, plot_roc_curve,roc_auc_score
cm = confusion_matrix(y_test, y_pred4)
print(cm)
#plot_confusion_matrix(classifier,x_test,y_test,values_format='d')
#plt.show()
print(accuracy_score(y_test, y_pred4))
print(f1_score(y_test, y_pred4,average='macro'))
print(precision_score(y_test,y_pred4,average='macro'))
print(recall_score(y_test,y_pred4,average='macro'))
print(balanced_accuracy_score(y_test,y_pred4))
print(classification_report(y_test, y_pred4))

#plot_roc_curve(classifier1,x_test,y_test)

print(roc_auc_score(y_test,y_pred4,average='macro'))

[[1873  173]
 [ 362 1752]]
0.8713942307692307
0.8712853347231926
0.8740805950201923
0.8721027068068299
0.8721027068068299
              precision    recall  f1-score   support

           0       0.84      0.92      0.88      2046
           1       0.91      0.83      0.87      2114

    accuracy                           0.87      4160
   macro avg       0.87      0.87      0.87      4160
weighted avg       0.87      0.87      0.87      4160

0.8721027068068298


In [ ]:
from sklearn.metrics import confusion_matrix,plot_confusion_matrix,accuracy_score ,f1_score, precision_score, recall_score,classification_report, plot_roc_curve,roc_auc_score
cm = confusion_matrix(y_test, y_pred5)
print(cm)
#plot_confusion_matrix(classifier,x_test,y_test,values_format='d')
#plt.show()
print(accuracy_score(y_test, y_pred5))
print(f1_score(y_test, y_pred5,average='macro'))
print(precision_score(y_test,y_pred5,average='macro'))
print(recall_score(y_test,y_pred5,average='macro'))
print(balanced_accuracy_score(y_test,y_pred5))
print(classification_report(y_test, y_pred5))

#plot_roc_curve(classifier1,x_test,y_test)

print(roc_auc_score(y_test,y_pred5,average='macro'))

[[1802  244]
 [ 220 1894]]
0.8884615384615384
0.8884069593948963
0.8885357420109385
0.8883373978439135
0.8883373978439135
              precision    recall  f1-score   support

           0       0.89      0.88      0.89      2046
           1       0.89      0.90      0.89      2114

    accuracy                           0.89      4160
   macro avg       0.89      0.89      0.89      4160
weighted avg       0.89      0.89      0.89      4160

0.8883373978439135


In [ ]:
from sklearn.metrics import confusion_matrix,plot_confusion_matrix,accuracy_score ,f1_score, precision_score, recall_score,classification_report, plot_roc_curve,roc_auc_score
cm = confusion_matrix(y_test, y_pred6)
print(cm)
#plot_confusion_matrix(classifier,x_test,y_test,values_format='d')
#plt.show()
print(accuracy_score(y_test, y_pred6))
print(f1_score(y_test, y_pred6,average='macro'))
print(precision_score(y_test,y_pred6,average='macro'))
print(recall_score(y_test,y_pred6,average='macro'))
print(balanced_accuracy_score(y_test,y_pred6))
print(classification_report(y_test, y_pred6))

#plot_roc_curve(classifier1,x_test,y_test)

print(roc_auc_score(y_test,y_pred6,average='macro'))

[[1892  154]
 [ 384 1730]]
0.8706730769230769
0.870476654338275
0.8747709879514476
0.8715425071972818
0.8715425071972818
              precision    recall  f1-score   support

           0       0.83      0.92      0.88      2046
           1       0.92      0.82      0.87      2114

    accuracy                           0.87      4160
   macro avg       0.87      0.87      0.87      4160
weighted avg       0.88      0.87      0.87      4160

0.8715425071972818


In [ ]:
from sklearn.metrics import confusion_matrix,plot_confusion_matrix,accuracy_score ,f1_score, precision_score, recall_score,classification_report, plot_roc_curve,roc_auc_score
cm = confusion_matrix(y_test, y_pred7)
print(cm)
#plot_confusion_matrix(classifier,x_test,y_test,values_format='d')
#plt.show()
print(accuracy_score(y_test, y_pred7))
print(f1_score(y_test, y_pred7,average='macro'))
print(precision_score(y_test,y_pred7,average='macro'))
print(recall_score(y_test,y_pred7,average='macro'))
print(balanced_accuracy_score(y_test,y_pred7))
print(classification_report(y_test, y_pred7))

#plot_roc_curve(classifier1,x_test,y_test)

print(roc_auc_score(y_test,y_pred7,average='macro'))

[[1899  147]
 [ 111 2003]]
0.9379807692307692
0.9379419829701257
0.9382020131898646
0.9378226985575843
0.9378226985575843
              precision    recall  f1-score   support

           0       0.94      0.93      0.94      2046
           1       0.93      0.95      0.94      2114

    accuracy                           0.94      4160
   macro avg       0.94      0.94      0.94      4160
weighted avg       0.94      0.94      0.94      4160

0.9378226985575843


In [ ]:
from sklearn.metrics import confusion_matrix,plot_confusion_matrix, balanced_accuracy_score, accuracy_score ,f1_score, precision_score, recall_score,classification_report, plot_roc_curve,roc_auc_score
cm = confusion_matrix(y_test, y_pred8)
print(cm)
#plot_confusion_matrix(classifier,x_test,y_test,values_format='d')
#plt.show()
print(accuracy_score(y_test, y_pred8))
print(f1_score(y_test, y_pred8,average='macro'))
print(precision_score(y_test,y_pred8,average='macro'))
print(recall_score(y_test,y_pred8,average='macro'))
print(balanced_accuracy_score(y_test,y_pred8))
print(classification_report(y_test, y_pred8))

#plot_roc_curve(classifier1,x_test,y_test)

print(roc_auc_score(y_test,y_pred8,average='macro'))

[[1891  155]
 [ 133 1981]]
0.9307692307692308
0.9307368116779882
0.930861497239123
0.930664258478828
0.930664258478828
              precision    recall  f1-score   support

           0       0.93      0.92      0.93      2046
           1       0.93      0.94      0.93      2114

    accuracy                           0.93      4160
   macro avg       0.93      0.93      0.93      4160
weighted avg       0.93      0.93      0.93      4160

0.9306642584788279


In [ ]:
from sklearn.metrics import confusion_matrix,plot_confusion_matrix, balanced_accuracy_score, accuracy_score ,f1_score, precision_score, recall_score,classification_report, plot_roc_curve,roc_auc_score
cm = confusion_matrix(y_test, y_pred9)
print(cm)
#plot_confusion_matrix(classifier,x_test,y_test,values_format='d')
#plt.show()
print(accuracy_score(y_test, y_pred9))
print(f1_score(y_test, y_pred9,average='macro'))
print(precision_score(y_test,y_pred9,average='macro'))
print(recall_score(y_test,y_pred9,average='macro'))
print(balanced_accuracy_score(y_test,y_pred9))
print(classification_report(y_test, y_pred9))

#plot_roc_curve(classifier1,x_test,y_test)

print(roc_auc_score(y_test,y_pred9,average='macro'))

[[1875  171]
 [ 127 1987]]
0.9283653846153846
0.9283134224511851
0.9286616997460371
0.9281733007432644
0.9281733007432644
              precision    recall  f1-score   support

           0       0.94      0.92      0.93      2046
           1       0.92      0.94      0.93      2114

    accuracy                           0.93      4160
   macro avg       0.93      0.93      0.93      4160
weighted avg       0.93      0.93      0.93      4160

0.9281733007432644


In [ ]:
from sklearn.metrics import confusion_matrix,plot_confusion_matrix, balanced_accuracy_score, accuracy_score ,f1_score, precision_score, recall_score,classification_report, plot_roc_curve,roc_auc_score
cm = confusion_matrix(y_test, y_pred10)
print(cm)
#plot_confusion_matrix(classifier,x_test,y_test,values_format='d')
#plt.show()
print(accuracy_score(y_test, y_pred10))
print(f1_score(y_test, y_pred10,average='macro'))
print(precision_score(y_test,y_pred10,average='macro'))
print(recall_score(y_test,y_pred10,average='macro'))
print(balanced_accuracy_score(y_test,y_pred10))
print(classification_report(y_test, y_pred10))

#plot_roc_curve(classifier1,x_test,y_test)

print(roc_auc_score(y_test,y_pred10,average='macro'))

[[1895  151]
 [  99 2015]]
0.9399038461538461
0.9398537984639586
0.9403186475400347
0.9396834028323027
0.9396834028323027
              precision    recall  f1-score   support

           0       0.95      0.93      0.94      2046
           1       0.93      0.95      0.94      2114

    accuracy                           0.94      4160
   macro avg       0.94      0.94      0.94      4160
weighted avg       0.94      0.94      0.94      4160

0.9396834028323026
